framework: terraform
# The goal is to reduce that list, not to grow it
skip-check:
    - CKV_AWS_2 # Ensure ALB protocol is HTTPS
    - CKV2_AWS_46 #"Ensure AWS Cloudfront Distribution with S3 have Origin Access set to enabled"
    - CKV2_AWS_28 #"Ensure public facing ALB are protected by WAF"
    - CKV2_AWS_41 #"Ensure an IAM role is attached to EC2 instance"
    - CKV2_AWS_5 #"Ensure that Security Groups are attached to another resource"
    - CKV2_AWS_11 #"Ensure VPC flow logging is enabled in all VPCs"
    - CKV2_AWS_12 #"Ensure the default security group of every VPC restricts all traffic"
    - CKV_AWS_23 #"Ensure every security groups rule has a description"
    - CKV_AWS_24 #"Ensure no security groups allow ingress from 0.0.0.0:0 to port 22"
    - CKV_AWS_260 #"Ensure no security groups allow ingress from 0.0.0.0:0 to port 80"
    - CKV_AWS_130 #"Ensure VPC subnets do not assign public IP by default"
    - CKV_AWS_79 #"Ensure Instance Metadata Service Version 1 is not enabled"
    - CKV_AWS_91 #"Ensure the ELBv2 (Application/Network) has access logging enabled"
    - CKV_AWS_150 #"Ensure that Load Balancer has deletion protection enabled"