name: 'Deploy Infra CI'

on:
    push:
        branches:
            - update-script

env:
    FORCE_COLOR: 3
    AWS_REGION: us-east-2
    TF_BUCKET: infra-task
    TF_KEY: infra/infra-task.tfstate
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v2
            - uses: hashicorp/setup-terraform@v1

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: "1.1.0"

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-region: ${{ env.AWS_REGION }}
                aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

            - name: Download Terraform state
              run: |
                aws s3 cp s3://${{ env.TF_BUCKET }}/${{ env.TF_KEY }} ${GITHUB_WORKSPACE}/terraform/terraform.tfstate
              # uses: aws-actions/amazon-s3-fetch-object@v1
              # with:
              #   region: ${{ env.AWS_REGION }}
              #   bucket: ${{ env.TF_BUCKET }}
              #   key: ${{ env.TF_KEY }}
              #   path: ${GITHUB_WORKSPACE}/terraform/terraform.tfstate

            - name: Terraform init
              run: terraform init -backend-config="bucket=${{ env.TF_BUCKET }}" -backend-config="key=${{ env.TF_KEY }}"

            # - name: Terraform apply
            #   run: terraform apply -auto-approve

            # - name: Terraform apply
            #   run: terraform apply -auto-approve